# https://blog.codeship.com/deploying-docker-rails-app/

FROM ruby:2.4.1
ENV LANG C.UTF-8
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs imagemagick
RUN mkdir /myapp
WORKDIR /myapp
ADD Gemfile /myapp/Gemfile
ADD Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
ADD . /myapp

RUN bundle exec rake assets:precompile

# Start puma
CMD bundle exec puma -C config/puma.rb