version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - SECRET_KEY_BASE=secret
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=enabled
      - RAILS_LOG_TO_STDOUT=enabled
    command: sh -c 'rm tmp/pids/* || true && bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db